### PR TITLE
Use NAMESPACE env variable to search on a specific namespace

### LINKED ISSUE #2: Search only in current or specific namespace
Hi,
would it maybe be possible to make the sidecar configurable to search only in a specific or the actual namespace?
In our setup we use namespaces to separate teams and so we don't have access to search in all namespaces.. which is btw not neccessary in our usecase.. so simply set the namespace where the sidecar is looking for config maps would already fit our needs.

Whats you opinion on such a change?
Thanks

### PR DESCRIPTION
**Pull request by eloo**
This will fix #2 
@Tim-Smyth what do you think?

### CODE REVIEW

**Comment by Tim-Smyth** [comment]
Looks good @eloo, could you please extend the Readme too?

**Comment by eloo** [comment]
of course ;) 
will do it soon

**Comment by eloo** [comment]
done

**Comment by Tim-Smyth** [comment]
Thank you very much @eloo

**Pull request merged**
