### PR TITLE
add option to skip tls verification

### PR DESCRIPTION
**Pull request by em-schmidt**

### CODE REVIEW

**Comment by em-schmidt** [comment]
fixes #18

**Comment by Tim-Smyth** [comment]
Hi @em-schmidt , thank you for your PR. Can you please update it to the cover the usecase merged in https://github.com/kiwigrid/k8s-sidecar/pull/12 ? Thank you very much :+1:

**Comment by em-schmidt** [comment]
@Tim-Smyth updated per your request.

**Comment by Tim-Smyth** [comment]
@em-schmidt Thank you for your adjustment. Just one more thing: Could you put the code in the main function to avoid code duplication please? Or would you see a problem with that?

**Comment by em-schmidt** [comment]
@Tim-Smyth pulled the xls up into main.

**Pull request merged**
