### PR TITLE
Update base img and pip pkg

### PR DESCRIPTION
**Pull request by naseemkullah**
In an effort to solve https://github.com/kiwigrid/k8s-sidecar/issues/13

As per @gochist suggestion

### CODE REVIEW

**Comment by gochist** [comment]
@naseemkullah I'm sorry that I deleted the suggestion when I found it doesn't fix the problem.

**Comment by naseemkullah** [comment]
np @gochist 

I'll leave this open as it's a good idea to update anyways

For more info:
Python 3.7 features: https://realpython.com/python37-new-features/
Kubernetes client release notes: https://github.com/kubernetes-client/python/blob/master/CHANGELOG.md

**Comment by Tim-Smyth** [comment]
Hi @naseemkullah and sorry for the delay. Thank you very much for your constribution

**Comment by naseemkullah** [comment]
My pleasure, thanks @Tim-Smyth !

**Pull request merged**
