### PR TITLE
Don't crash on exceptions

### PR DESCRIPTION
**Pull request by eloo**
Improve error handling related to #5

### CODE REVIEW

**Comment by Tim-Smyth** [comment]
With this PR we would take to error handling away from k8s. For example while testing I worked with a dummy notification address and the container didn't fail as expected but keep retrying.

**Comment by eloo** [comment]
@Tim-Smyth ah yes thats right.
but at the moment the container is also not crashing everytime but stops doing anything.. 
so i'm facing not updated files but get restarts for the container.. 
and with this PR i simple want to keep the functionality alive

**Comment by Tim-Smyth** [comment]
If your PR should fix that issue, there should be an exception thrown if he hangs right? And if it does the container should restart anyway? If he hangs without throwing an exception we have to find an different approach to solve it.
About the configmap being invalid: we just use fields that are mandatory/controlled by k8s anyway, so we should not run into problems there.

**Comment by eloo** [comment]
@Tim-Smyth but why should we keep the container restarting for a simple exception? this consume way more time than simply "ok there was an error i will log it and keep going on"

i really didn't see any advantage of restarting the whole container

**Comment by Tim-Smyth** [comment]
The advantage I see is that k8s will make sure that the container doesn't misbehave: If the container fails a few times the backoff strategy will kick in and reduce the "load" on the cluster.
While playing around with the sidecar I configured a dummy url for the notifications, which resulted in repeated restarts of the watchForChanges function, resulting in unnecessary load.

**Comment by Tim-Smyth** [comment]
@eloo You are right about the configuration, but its just an example. With your PR we just broadly cover all exceptions. What if a the permissions of the sidecar's user are modified and now we always get an exception that we are not allowed to access the k8s api? The pod would just try accessing the api as fast as he can without the operator noticing it (or its malfunction).

**Comment by eloo** [comment]
yes that true.. okay, i will have a look if i can be more specific about the exception i'm catching.

**Comment by ahma** [comment]
Hi 
We had a similar problem with the AKS (Azure), and OCI (Oracle). 
I understand your opinion @Tim-Smyth and why you don't want to merge the fix like this, but in this case, I don't have a better idea. 
I made a working solution based on @eloo 's  idea. 
code:  https://github.com/banzaicloud/k8s-sidecar/pull/1/files
Image: banzaicloud/k8s-sidecar:0.0.7
I hope it will be helpful for someone.

**Comment by MihaiAnei** [comment]
Coming from the above: https://github.com/helm/charts/issues/9136

Did you guys know about this: https://github.com/kubernetes-client/python-base/issues/57 ?

**Comment by Tim-Smyth** [comment]
This issue is now covered with PR https://github.com/kiwigrid/k8s-sidecar/pull/15
Hope the new version 0.0.12 solves your issues. Thank you for your valuable input :+1: 
If there are still problems please let me know

**Pull request closed without merging**
