### PR TITLE
Adding support for req-username-file and req-password-file cli flags

### PR DESCRIPTION
**Pull request by wasim-nihal**
Changes for https://github.com/kiwigrid/k8s-sidecar/issues/318

### CODE REVIEW

**Comment by ChristianGeie** [comment]
thx for contributing.
lgtm so far.
Can you please provide a little test for this use case?

**Comment by wasim-nihal** [comment]
> Can you please provide a little test for this use case?

Sure, thanks for your review. I will add the test.

**Comment by wasim-nihal** [comment]
Hi @ChristianGeie  , I have added tests for the change. Can you please trigger the test execution and let me know if something needs to be updated.

**Comment by ChristianGeie** [comment]
@wasim-nihal i triggered the checks but after a couple of minutes i cancel because of observing an "endless" loop while `sidecar-basicauth-args` becomes ready. I haven't had the chance to look at it in detail yet.

**Comment by wasim-nihal** [comment]
@ChristianGeie , I suspect the pod did not come up because the image name `k8s-sidecar:testing` was not found. I have corrected it in the latest [commit ](https://github.com/kiwigrid/k8s-sidecar/pull/322/commits/128c189e8e27930db628477c5d7c836de400066d)with the right image `kiwigrid/k8s-sidecar:testing` . Could you please re-run it once?

**Comment by ChristianGeie** [comment]
Sure.

**Comment by ChristianGeie** [comment]
looks much better now

**Comment by wasim-nihal** [comment]
Thanks @ChristianGeie

**Comment by wasim-nihal** [comment]
@ChristianGeie, could you please let me know if any further changes are needed? I shall work on it.

**Comment by ChristianGeie** [comment]
@wasim-nihal workflow for checks did not start, can you do a empty commit followed by a `git push` pls?

**Comment by wasim-nihal** [comment]
> @wasim-nihal workflow for checks did not start, can you do a empty commit followed by a `git push` pls?

Thanks, done rebsing. Workflows seem to have passed.

**Pull request merged**
